### ISSUE TITLE
Demo opens empty on Firefox

### ISSUE THREAD

**Issue by fczuardi** [OpenBazaar/OpenBazaar-Design#7]
Steps to reproduce:

- follow the README instructions to have the webserver running locally with a copy of the demo
- open http://localhost:9080/

Expected behavior:

A welcome dialog with the setup wizard appears for you to start using the demo.

Actual behavior:

Only an empty screen appears, the errors on the console dont give much information (and are very similar to the ones in chrome, but in chrome the site works).

Tested on Firefox 39.0

**Comment by morebrownies** [comment]
This is only a prototype and will only be useable in Chrome. There are no plans to support cross-browsers for the prototype; not worth the time when people can just open it in Chrome to see what it looks like.

**Comment by fczuardi** [comment]
Do you know what the uninplemented standard in Firefox that causes this issue so I can file a bug on Mozilla's Bugzilla? Being compatible with the latest standards is an important thing for the Firefox project…

Or the chrome-only proprietary feature if that's the case, can you provide me any hints?

Thanks!

**Comment by morebrownies** [comment]
To be honest, I haven't even opened it in Firefox, so I have no idea what the issue(s) are. If someone wanted to dig into it, they can, but it's likely issues related to how I coded the prototype and not an actual bug in Firefox.

The production application will be built on Electron / Chromium, so there's no reason to really be considering Firefox.

**Comment by fczuardi** [comment]
ok, got it :(

**Comment by hoffmabc** [comment]
You should be able to see in Firebug what's happening I imagine.
