### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by rghose** [OpenBazaar/OpenBazaar-Design#8]
http://openbazaar-design.divshot.io/ here's what is seen:

Site Unavailable
Divshot, the hosting provider for this website, has ceased operation as of December 22, 2015. Divshot technology now powers Firebase Hosting.

If this is your website, please update your DNS to point to a new hosting provider!

**Comment by morebrownies** [comment]
This was a prototype from many months ago and is no longer up to date.
